name: 'Send Google Chat Notification'
description: 'Send a notification to Google Chat'
inputs:
  webhook-url:
    description: 'The Google Chat webhook URL'
    required: true
  creator-name:
    description: 'The creator of the message'
    required: true
  asset-url:
    description: 'The URL to download the asset'
    required: false
  title:
    description: 'The title of the notification'
    required: false
    default: 'Notification'
  job-status:
    description: 'The status of the job'
    required: false
    default: ''
  commit-id:
    description: 'The commit ID'
    required: false
    default: ''
  description:
    description: 'this will be the description of the notification'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
