name: 'Send Google Chat Notification'
description: 'Send a notification to Google Chat'
inputs:
  webhook-url:
    description: 'The Google Chat webhook URL'
    required: true
  creator:
    description: 'The creator of the message'
    required: true
  apk-url:
    description: 'The URL to download the APK'
    required: true
  title:
    description: 'The title of the notification'
    required: false
    default: 'Notification'
  icon-url:
    description: 'The URL of the icon to display'
    required: false
    default: ''
  body:
    description: 'The body of the notification'
    required: false
    default: ''
  job-status:
    description: 'The status of the job'
    required: false
    default: ''
  commit-id:
    description: 'The commit ID'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'index.js'
